# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 819)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.query_block = QtWidgets.QVBoxLayout()
        self.query_block.setObjectName("query_block")
        spacerItem = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.query_block.addItem(spacerItem)
        self.query_content = QtWidgets.QHBoxLayout()
        self.query_content.setObjectName("query_content")
        self.content_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content_label.sizePolicy().hasHeightForWidth())
        self.content_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.content_label.setFont(font)
        self.content_label.setAlignment(QtCore.Qt.AlignCenter)
        self.content_label.setObjectName("content_label")
        self.query_content.addWidget(self.content_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.query_content.addItem(spacerItem1)
        self.content_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content_input.sizePolicy().hasHeightForWidth())
        self.content_input.setSizePolicy(sizePolicy)
        self.content_input.setMaximumSize(QtCore.QSize(280, 30))
        self.content_input.setAlignment(QtCore.Qt.AlignCenter)
        self.content_input.setObjectName("content_input")
        self.query_content.addWidget(self.content_input)
        self.query_block.addLayout(self.query_content)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.query_block.addItem(spacerItem2)
        self.query_data = QtWidgets.QHBoxLayout()
        self.query_data.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.query_data.setObjectName("query_data")
        self.data_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_label.sizePolicy().hasHeightForWidth())
        self.data_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.data_label.setFont(font)
        self.data_label.setAlignment(QtCore.Qt.AlignCenter)
        self.data_label.setObjectName("data_label")
        self.query_data.addWidget(self.data_label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.query_data.addItem(spacerItem3)
        self.year_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year_input.sizePolicy().hasHeightForWidth())
        self.year_input.setSizePolicy(sizePolicy)
        self.year_input.setMaximumSize(QtCore.QSize(55, 30))
        self.year_input.setAlignment(QtCore.Qt.AlignCenter)
        self.year_input.setObjectName("year_input")
        self.query_data.addWidget(self.year_input)
        self.year_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.year_label.sizePolicy().hasHeightForWidth())
        self.year_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.year_label.setFont(font)
        self.year_label.setAlignment(QtCore.Qt.AlignCenter)
        self.year_label.setObjectName("year_label")
        self.query_data.addWidget(self.year_label)
        self.month_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.month_input.sizePolicy().hasHeightForWidth())
        self.month_input.setSizePolicy(sizePolicy)
        self.month_input.setMaximumSize(QtCore.QSize(55, 30))
        self.month_input.setAlignment(QtCore.Qt.AlignCenter)
        self.month_input.setObjectName("month_input")
        self.query_data.addWidget(self.month_input)
        self.month_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.month_label.sizePolicy().hasHeightForWidth())
        self.month_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.month_label.setFont(font)
        self.month_label.setAlignment(QtCore.Qt.AlignCenter)
        self.month_label.setObjectName("month_label")
        self.query_data.addWidget(self.month_label)
        self.day_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.day_input.sizePolicy().hasHeightForWidth())
        self.day_input.setSizePolicy(sizePolicy)
        self.day_input.setMaximumSize(QtCore.QSize(55, 30))
        self.day_input.setAlignment(QtCore.Qt.AlignCenter)
        self.day_input.setObjectName("day_input")
        self.query_data.addWidget(self.day_input)
        self.day_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.day_label.sizePolicy().hasHeightForWidth())
        self.day_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.day_label.setFont(font)
        self.day_label.setAlignment(QtCore.Qt.AlignCenter)
        self.day_label.setWordWrap(False)
        self.day_label.setIndent(-1)
        self.day_label.setObjectName("day_label")
        self.query_data.addWidget(self.day_label)
        self.query_block.addLayout(self.query_data)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.query_block.addItem(spacerItem4)
        self.query_length = QtWidgets.QHBoxLayout()
        self.query_length.setObjectName("query_length")
        self.length_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.length_label.sizePolicy().hasHeightForWidth())
        self.length_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.length_label.setFont(font)
        self.length_label.setAlignment(QtCore.Qt.AlignCenter)
        self.length_label.setObjectName("length_label")
        self.query_length.addWidget(self.length_label)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.query_length.addItem(spacerItem5)
        self.min_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_label.sizePolicy().hasHeightForWidth())
        self.min_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.min_label.setFont(font)
        self.min_label.setAlignment(QtCore.Qt.AlignCenter)
        self.min_label.setObjectName("min_label")
        self.query_length.addWidget(self.min_label)
        self.min_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_input.sizePolicy().hasHeightForWidth())
        self.min_input.setSizePolicy(sizePolicy)
        self.min_input.setMaximumSize(QtCore.QSize(80, 30))
        self.min_input.setAlignment(QtCore.Qt.AlignCenter)
        self.min_input.setObjectName("min_input")
        self.query_length.addWidget(self.min_input)
        self.max_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_label.sizePolicy().hasHeightForWidth())
        self.max_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.max_label.setFont(font)
        self.max_label.setAlignment(QtCore.Qt.AlignCenter)
        self.max_label.setObjectName("max_label")
        self.query_length.addWidget(self.max_label)
        self.max_input = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_input.sizePolicy().hasHeightForWidth())
        self.max_input.setSizePolicy(sizePolicy)
        self.max_input.setMaximumSize(QtCore.QSize(80, 30))
        self.max_input.setAlignment(QtCore.Qt.AlignCenter)
        self.max_input.setObjectName("max_input")
        self.query_length.addWidget(self.max_input)
        self.query_block.addLayout(self.query_length)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.query_block.addItem(spacerItem6)
        self.submit_block = QtWidgets.QHBoxLayout()
        self.submit_block.setObjectName("submit_block")
        spacerItem7 = QtWidgets.QSpacerItem(80, 27, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.submit_block.addItem(spacerItem7)
        self.dele = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dele.sizePolicy().hasHeightForWidth())
        self.dele.setSizePolicy(sizePolicy)
        self.dele.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.dele.setFont(font)
        self.dele.setObjectName("dele")
        self.submit_block.addWidget(self.dele)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.submit_block.addItem(spacerItem8)
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit.sizePolicy().hasHeightForWidth())
        self.submit.setSizePolicy(sizePolicy)
        self.submit.setMinimumSize(QtCore.QSize(0, 0))
        self.submit.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        self.submit.setFont(font)
        self.submit.setDefault(False)
        self.submit.setObjectName("submit")
        self.submit_block.addWidget(self.submit)
        spacerItem9 = QtWidgets.QSpacerItem(80, 27, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.submit_block.addItem(spacerItem9)
        self.query_block.addLayout(self.submit_block)
        spacerItem10 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.query_block.addItem(spacerItem10)
        self.horizontalLayout_5.addLayout(self.query_block)
        spacerItem11 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.show_block = QtWidgets.QVBoxLayout()
        self.show_block.setObjectName("show_block")
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.show_block.addItem(spacerItem12)
        self.show_box = QtWidgets.QSplitter(self.centralwidget)
        self.show_box.setOrientation(QtCore.Qt.Vertical)
        self.show_box.setObjectName("show_box")
        self.stat_box = QtWidgets.QSplitter(self.show_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stat_box.sizePolicy().hasHeightForWidth())
        self.stat_box.setSizePolicy(sizePolicy)
        self.stat_box.setOrientation(QtCore.Qt.Horizontal)
        self.stat_box.setObjectName("stat_box")
        self.date_show = QtWidgets.QTextEdit(self.stat_box)
        self.date_show.setObjectName("date_show")
        self.stat_show = QtWidgets.QTextEdit(self.stat_box)
        self.stat_show.setObjectName("stat_show")
        self.detail_show = QtWidgets.QTextEdit(self.show_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detail_show.sizePolicy().hasHeightForWidth())
        self.detail_show.setSizePolicy(sizePolicy)
        self.detail_show.setMinimumSize(QtCore.QSize(700, 0))
        self.detail_show.setObjectName("detail_show")
        self.show_block.addWidget(self.show_box)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.show_block.addItem(spacerItem13)
        self.horizontalLayout_5.addLayout(self.show_block)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1119, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.content_label.setText(_translate("MainWindow", "内容:"))
        self.data_label.setText(_translate("MainWindow", "日期:"))
        self.year_label.setText(_translate("MainWindow", "年"))
        self.month_label.setText(_translate("MainWindow", "月"))
        self.day_label.setText(_translate("MainWindow", "日"))
        self.length_label.setText(_translate("MainWindow", "长度:"))
        self.min_label.setText(_translate("MainWindow", "最短"))
        self.max_label.setText(_translate("MainWindow", "最长"))
        self.dele.setText(_translate("MainWindow", "清空"))
        self.submit.setText(_translate("MainWindow", "查询"))
